### ISSUE TITLE
how to get the date value like 16/03/2019

### ISSUE THREAD

**Issue by tayeh** [ZulNs/Datepicker.js#2]
hi 
can i get the date in format 16/03/2019 also i need it for hijri date ?

**Comment by tayeh** [comment]
plus i need to reconvert the date to string :)

**Comment by ZulNs** [comment]
@Tayeh,
Assume `Datepicker` object is `picker`
Then `picker.getPickedDate()` will return [`Date`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) or [`HijriDate`](https://zulns.github.io/HijriDate.js/hijri-date-api-doc.html) object depend on `Datepicker` dates mode.
To extract the date in format DD/MM/YYYY you can use following code snippet:
```javascript
let date = picker.getPickedDate();
let formattedDate = HijriDate.toNDigit(date.getDate(), 2) + '/' + HijriDate.toNDigit(date.getMonth()+1, 2) + '/' + HijriDate.toNDigit(date.getFullYear(), 4);
```
