### ISSUE TITLE
adjust hijri date 

### ISSUE THREAD

**Issue by mhdbashar** [ZulNs/Datepicker.js#3]
hi,
today is 17-12-1440 not 16-12-1440 is there any manual adjustment to fix this issue
thanks

**Comment by ZulNs** [comment]
I determined the Hijri dates based on calculations in the [HijriDate](https://github.com/ZulNs/HijriDate.js) repo. There may be an error in the calculation, which I will try to correct when there is spare time. Sorry I haven't provided a feature for manual date adjustment.
